namespace SoundBoard88.Keyboard;

/// <summary>
/// Selectable keyboard layout metadata. Layout variants can share the same physical
/// key geometry while exposing a locale-specific name in settings.
/// </summary>
public sealed record KeyboardLayoutInfo(
    string Code,
    string Label,
    string Geometry,
    string Region
);

public static class KeyboardLayoutCatalog
{
    public static readonly KeyboardLayoutInfo[] Layouts =
    [
        new("system", "System Default", "system", "Auto-detect"),
        new("ja-JP-jis", "Japanese JIS", "jis", "Japan"),
        new("en-US-ansi", "English US (ANSI)", "us", "United States"),
        new("en-GB-iso", "English UK (ISO)", "us", "United Kingdom"),
        new("en-AU-ansi", "English Australia", "us", "Australia"),
        new("en-CA-ansi", "English Canada", "us", "Canada"),
        new("en-IN-ansi", "English India", "us", "India"),
        new("en-NZ-ansi", "English New Zealand", "us", "New Zealand"),
        new("en-ZA-ansi", "English South Africa", "us", "South Africa"),
        new("de-DE-qwertz", "German QWERTZ", "us", "Germany"),
        new("de-AT-qwertz", "Austrian German QWERTZ", "us", "Austria"),
        new("de-CH-qwertz", "Swiss German QWERTZ", "us", "Switzerland"),
        new("fr-FR-azerty", "French AZERTY", "us", "France"),
        new("fr-BE-azerty", "Belgian French AZERTY", "us", "Belgium"),
        new("fr-CH-qwertz", "Swiss French QWERTZ", "us", "Switzerland"),
        new("fr-CA-qwerty", "Canadian French QWERTY", "us", "Canada"),
        new("es-ES-qwerty", "Spanish Spain", "us", "Spain"),
        new("es-Latam-qwerty", "Spanish Latin America", "us", "Latin America"),
        new("es-US-qwerty", "Spanish United States", "us", "United States"),
        new("pt-PT-qwerty", "Portuguese Portugal", "us", "Portugal"),
        new("pt-BR-abnt2", "Portuguese Brazil ABNT2", "us", "Brazil"),
        new("it-IT-qwerty", "Italian", "us", "Italy"),
        new("nl-NL-qwerty", "Dutch", "us", "Netherlands"),
        new("nl-BE-azerty", "Belgian Dutch AZERTY", "us", "Belgium"),
        new("da-DK-qwerty", "Danish", "us", "Denmark"),
        new("sv-SE-qwerty", "Swedish", "us", "Sweden"),
        new("no-NO-qwerty", "Norwegian", "us", "Norway"),
        new("fi-FI-qwerty", "Finnish", "us", "Finland"),
        new("is-IS-qwerty", "Icelandic", "us", "Iceland"),
        new("pl-PL-programmers", "Polish Programmers", "us", "Poland"),
        new("pl-PL-214", "Polish 214", "us", "Poland"),
        new("cs-CZ-qwertz", "Czech QWERTZ", "us", "Czechia"),
        new("cs-CZ-qwerty", "Czech QWERTY", "us", "Czechia"),
        new("sk-SK-qwertz", "Slovak QWERTZ", "us", "Slovakia"),
        new("hu-HU-qwertz", "Hungarian QWERTZ", "us", "Hungary"),
        new("ro-RO-programmers", "Romanian Programmers", "us", "Romania"),
        new("sl-SI-qwertz", "Slovenian QWERTZ", "us", "Slovenia"),
        new("hr-HR-qwertz", "Croatian QWERTZ", "us", "Croatia"),
        new("sr-RS-latin", "Serbian Latin", "us", "Serbia"),
        new("sr-RS-cyrillic", "Serbian Cyrillic", "us", "Serbia"),
        new("bs-BA-qwertz", "Bosnian QWERTZ", "us", "Bosnia & Herzegovina"),
        new("tr-TR-q", "Turkish Q", "us", "Türkiye"),
        new("tr-TR-f", "Turkish F", "us", "Türkiye"),
        new("el-GR-220", "Greek 220", "us", "Greece"),
        new("el-GR-319", "Greek 319", "us", "Greece"),
        new("ru-RU-jcuken", "Russian JCUKEN", "us", "Russia"),
        new("ru-RU-phonetic", "Russian Phonetic", "us", "Russia"),
        new("uk-UA-jcuken", "Ukrainian", "us", "Ukraine"),
        new("be-BY-jcuken", "Belarusian", "us", "Belarus"),
        new("bg-BG-bds", "Bulgarian BDS", "us", "Bulgaria"),
        new("bg-BG-phonetic", "Bulgarian Phonetic", "us", "Bulgaria"),
        new("kk-KZ-cyrillic", "Kazakh Cyrillic", "us", "Kazakhstan"),
        new("ka-GE-qwerty", "Georgian QWERTY", "us", "Georgia"),
        new("hy-AM-eastern", "Armenian Eastern", "us", "Armenia"),
        new("he-IL-standard", "Hebrew Standard", "us", "Israel"),
        new("ar-001-101", "Arabic 101", "us", "Arabic"),
        new("ar-001-102", "Arabic 102", "us", "Arabic"),
        new("fa-IR-standard", "Persian Standard", "us", "Iran"),
        new("ur-PK-standard", "Urdu Standard", "us", "Pakistan"),
        new("hi-IN-inscript", "Hindi InScript", "us", "India"),
        new("hi-IN-phonetic", "Hindi Phonetic", "us", "India"),
        new("as-IN-inscript", "Assamese InScript", "us", "India"),
        new("bn-IN-inscript", "Bengali India InScript", "us", "India"),
        new("bn-BD-national", "Bengali Bangladesh National", "us", "Bangladesh"),
        new("brx-IN-inscript", "Bodo InScript", "us", "India"),
        new("doi-IN-inscript", "Dogri InScript", "us", "India"),
        new("gu-IN-inscript", "Gujarati InScript", "us", "India"),
        new("kn-IN-inscript", "Kannada InScript", "us", "India"),
        new("kok-IN-inscript", "Konkani InScript", "us", "India"),
        new("ks-IN-inscript", "Kashmiri InScript", "us", "India"),
        new("mai-IN-inscript", "Maithili InScript", "us", "India"),
        new("ml-IN-inscript", "Malayalam InScript", "us", "India"),
        new("mni-IN-inscript", "Manipuri InScript", "us", "India"),
        new("mr-IN-inscript", "Marathi InScript", "us", "India"),
        new("ne-IN-inscript", "Nepali InScript", "us", "India"),
        new("or-IN-inscript", "Odia InScript", "us", "India"),
        new("pa-IN-inscript", "Punjabi Gurmukhi InScript", "us", "India"),
        new("sa-IN-inscript", "Sanskrit InScript", "us", "India"),
        new("sat-IN-inscript", "Santali InScript", "us", "India"),
        new("sd-IN-inscript", "Sindhi Devanagari InScript", "us", "India"),
        new("ta-IN-tamil99", "Tamil 99", "us", "India"),
        new("ta-IN-inscript", "Tamil InScript", "us", "India"),
        new("te-IN-inscript", "Telugu InScript", "us", "India"),
        new("si-LK-wijesekara", "Sinhala Wijesekara", "us", "Sri Lanka"),
        new("th-TH-kedmanee", "Thai Kedmanee", "us", "Thailand"),
        new("th-TH-pattachote", "Thai Pattachote", "us", "Thailand"),
        new("lo-LA-standard", "Lao Standard", "us", "Laos"),
        new("km-KH-niDA", "Khmer NiDA", "us", "Cambodia"),
        new("my-MM-standard", "Myanmar Standard", "us", "Myanmar"),
        new("vi-VN-telex", "Vietnamese Telex", "us", "Vietnam"),
        new("vi-VN-vni", "Vietnamese VNI", "us", "Vietnam"),
        new("ko-KR-dubeolsik", "Korean Dubeolsik", "us", "Korea"),
        new("ko-KR-sebeolsik", "Korean Sebeolsik", "us", "Korea"),
        new("zh-CN-pinyin", "Chinese Simplified Pinyin", "us", "China"),
        new("zh-CN-wubi", "Chinese Simplified Wubi", "us", "China"),
        new("zh-TW-zhuyin", "Chinese Traditional Zhuyin", "us", "Taiwan"),
        new("zh-TW-cangjie", "Chinese Traditional Cangjie", "us", "Taiwan"),
        new("zh-HK-cangjie", "Chinese Hong Kong Cangjie", "us", "Hong Kong"),
        new("ja-JP-kana", "Japanese Kana Input", "jis", "Japan"),
        new("ja-JP-romaji", "Japanese Romaji Input", "jis", "Japan"),
        new("id-ID-qwerty", "Indonesian", "us", "Indonesia"),
        new("ms-MY-qwerty", "Malay", "us", "Malaysia"),
        new("fil-PH-qwerty", "Filipino", "us", "Philippines"),
        new("sw-KE-qwerty", "Swahili", "us", "Kenya"),
        new("am-ET-gez", "Amharic Geez", "us", "Ethiopia"),
        new("ti-ET-gez", "Tigrinya Geez", "us", "Ethiopia"),
        new("chr-US-cherokee", "Cherokee", "us", "United States"),
    ];
}
