namespace SoundBoard88.SetupLang;

public sealed record SetupLanguageInfo(string Code, string Name);

public static class SetupLanguageCatalog
{
    public static readonly SetupLanguageInfo[] Languages =
    [
        new("af-NA", "Afrikaans (Namibia)"),
        new("af-ZA", "Afrikaans (South Africa)"),
        new("agq-CM", "Aghem (Cameroon)"),
        new("ak-GH", "Akan (Ghana)"),
        new("am-ET", "አማርኛ (ኢትዮጵያ)"),
        new("ar-001", "العربية (العالم)"),
        new("ar-AE", "العربية (الإمارات)"),
        new("ar-BH", "العربية (البحرين)"),
        new("ar-DJ", "العربية (جيبوتي)"),
        new("ar-DZ", "العربية (الجزائر)"),
        new("ar-EG", "العربية (مصر)"),
        new("ar-ER", "العربية (إريتريا)"),
        new("ar-IL", "العربية (إسرائيل)"),
        new("ar-IQ", "العربية (العراق)"),
        new("ar-JO", "العربية (الأردن)"),
        new("ar-KM", "العربية (جزر القمر)"),
        new("ar-KW", "العربية (الكويت)"),
        new("ar-LB", "العربية (لبنان)"),
        new("ar-LY", "العربية (ليبيا)"),
        new("ar-MA", "العربية (المغرب)"),
        new("ar-MR", "العربية (موريتانيا)"),
        new("ar-OM", "العربية (عُمان)"),
        new("ar-PS", "العربية (فلسطين)"),
        new("ar-QA", "العربية (قطر)"),
        new("ar-SA", "العربية (السعودية)"),
        new("ar-SD", "العربية (السودان)"),
        new("ar-SO", "العربية (الصومال)"),
        new("ar-SS", "العربية (جنوب السودان)"),
        new("ar-SY", "العربية (سوريا)"),
        new("ar-TD", "العربية (تشاد)"),
        new("ar-TN", "العربية (تونس)"),
        new("ar-YE", "العربية (اليمن)"),
        new("as-IN", "অসমীয়া (ভাৰত)"),
        new("asa-TZ", "Asu (Tanzania)"),
        new("ast-ES", "Asturianu (España)"),
        new("az-Cyrl-AZ", "Азәрбајҹан (Кирил, Азәрбајҹан)"),
        new("az-Latn-AZ", "Azərbaycanca (Latın, Azərbaycan)"),
        new("bas-CM", "Basaa (Cameroon)"),
        new("be-BY", "Беларуская (Беларусь)"),
        new("bem-ZM", "Bemba (Zambia)"),
        new("bez-TZ", "Bena (Tanzania)"),
        new("bg-BG", "Български (България)"),
        new("bho-IN", "भोजपुरी (भारत)"),
        new("bm-ML", "Bamanankan (Mali)"),
        new("bn-BD", "বাংলা (বাংলাদেশ)"),
        new("bn-IN", "বাংলা (ভারত)"),
        new("bo-CN", "བོད་སྐད་ (རྒྱ་ནག)"),
        new("bo-IN", "བོད་སྐད་ (རྒྱ་གར)"),
        new("br-FR", "Brezhoneg (Frañs)"),
        new("brx-IN", "बड़ो (भारत)"),
        new("bs-Cyrl-BA", "Босански (ћирилица, БиХ)"),
        new("bs-Latn-BA", "Bosanski (latinica, BiH)"),
        new("ca-AD", "Català (Andorra)"),
        new("ca-ES", "Català (Espanya)"),
        new("ca-FR", "Català (França)"),
        new("ca-IT", "Català (Itàlia)"),
        new("ccp-BD", "𑄌𑄋𑄴𑄟𑄳𑄦 (Bangladesh)"),
        new("ccp-IN", "𑄌𑄋𑄴𑄟𑄳𑄦 (India)"),
        new("ce-RU", "Нохчийн (Росси)"),
        new("ceb-PH", "Cebuano (Pilipinas)"),
        new("cgg-UG", "Chiga (Uganda)"),
        new("chr-US", "ᏣᎳᎩ (US)"),
        new("ckb-IQ", "کوردیی ناوەندی (عێراق)"),
        new("ckb-IR", "کوردیی ناوەندی (ئێران)"),
        new("cs-CZ", "Čeština (Česko)"),
        new("cy-GB", "Cymraeg (Y Deyrnas Unedig)"),
        new("da-DK", "Dansk (Danmark)"),
        new("da-GL", "Dansk (Grønland)"),
        new("dav-KE", "Taita (Kenya)"),
        new("de", "Deutsch"),
        new("de-AT", "Deutsch (Österreich)"),
        new("de-BE", "Deutsch (Belgien)"),
        new("de-CH", "Deutsch (Schweiz)"),
        new("de-DE", "Deutsch (Deutschland)"),
        new("de-IT", "Deutsch (Italien)"),
        new("de-LI", "Deutsch (Liechtenstein)"),
        new("de-LU", "Deutsch (Luxemburg)"),
        new("dje-NE", "Zarma (Niger)"),
        new("doi-IN", "डोगरी (भारत)"),
        new("dsb-DE", "Dolnoserbšćina (Nimska)"),
        new("dua-CM", "Duala (Cameroon)"),
        new("dyo-SN", "Jola-Fonyi (Senegal)"),
        new("dz-BT", "རྫོང་ཁ (འབྲུག)"),
        new("ebu-KE", "Embu (Kenya)"),
        new("ee-GH", "Eʋegbe (Ghana)"),
        new("ee-TG", "Eʋegbe (Togo)"),
        new("el-CY", "Ελληνικά (Κύπρος)"),
        new("el-GR", "Ελληνικά (Ελλάδα)"),
        new("en", "English (US)"),
        new("en-001", "English (World)"),
        new("en-150", "English (Europe)"),
        new("en-AE", "English (United Arab Emirates)"),
        new("en-AG", "English (Antigua & Barbuda)"),
        new("en-AI", "English (Anguilla)"),
        new("en-AS", "English (American Samoa)"),
        new("en-AT", "English (Austria)"),
        new("en-AU", "English (Australia)"),
        new("en-BB", "English (Barbados)"),
        new("en-BE", "English (Belgium)"),
        new("en-BI", "English (Burundi)"),
        new("en-BM", "English (Bermuda)"),
        new("en-BS", "English (Bahamas)"),
        new("en-BW", "English (Botswana)"),
        new("en-BZ", "English (Belize)"),
        new("en-CA", "English (Canada)"),
        new("en-CC", "English (Cocos Islands)"),
        new("en-CH", "English (Switzerland)"),
        new("en-CK", "English (Cook Islands)"),
        new("en-CM", "English (Cameroon)"),
        new("en-CX", "English (Christmas Island)"),
        new("en-CY", "English (Cyprus)"),
        new("en-DE", "English (Germany)"),
        new("en-DG", "English (Diego Garcia)"),
        new("en-DK", "English (Denmark)"),
        new("en-DM", "English (Dominica)"),
        new("en-ER", "English (Eritrea)"),
        new("en-FI", "English (Finland)"),
        new("en-FJ", "English (Fiji)"),
        new("en-FK", "English (Falkland Islands)"),
        new("en-FM", "English (Micronesia)"),
        new("en-GB", "English (UK)"),
        new("en-GD", "English (Grenada)"),
        new("en-GG", "English (Guernsey)"),
        new("en-GH", "English (Ghana)"),
        new("en-GI", "English (Gibraltar)"),
        new("en-GM", "English (Gambia)"),
        new("en-GU", "English (Guam)"),
        new("en-GY", "English (Guyana)"),
        new("en-HK", "English (Hong Kong)"),
        new("en-IE", "English (Ireland)"),
        new("en-IL", "English (Israel)"),
        new("en-IM", "English (Isle of Man)"),
        new("en-IN", "English (India)"),
        new("en-IO", "English (British Indian Ocean Territory)"),
        new("en-JE", "English (Jersey)"),
        new("en-JM", "English (Jamaica)"),
        new("en-KE", "English (Kenya)"),
        new("en-KI", "English (Kiribati)"),
        new("en-KN", "English (St. Kitts & Nevis)"),
        new("en-KY", "English (Cayman Islands)"),
        new("en-LC", "English (St. Lucia)"),
        new("en-LR", "English (Liberia)"),
        new("en-LS", "English (Lesotho)"),
        new("en-MG", "English (Madagascar)"),
        new("en-MH", "English (Marshall Islands)"),
        new("en-MO", "English (Macao)"),
        new("en-MP", "English (Northern Mariana Islands)"),
        new("en-MS", "English (Montserrat)"),
        new("en-MT", "English (Malta)"),
        new("en-MU", "English (Mauritius)"),
        new("en-MW", "English (Malawi)"),
        new("en-MY", "English (Malaysia)"),
        new("en-NA", "English (Namibia)"),
        new("en-NF", "English (Norfolk Island)"),
        new("en-NG", "English (Nigeria)"),
        new("en-NL", "English (Netherlands)"),
        new("en-NR", "English (Nauru)"),
        new("en-NU", "English (Niue)"),
        new("en-NZ", "English (New Zealand)"),
        new("en-PG", "English (Papua New Guinea)"),
        new("en-PH", "English (Philippines)"),
        new("en-PK", "English (Pakistan)"),
        new("en-PN", "English (Pitcairn Islands)"),
        new("en-PR", "English (Puerto Rico)"),
        new("en-PW", "English (Palau)"),
        new("en-RW", "English (Rwanda)"),
        new("en-SB", "English (Solomon Islands)"),
        new("en-SC", "English (Seychelles)"),
        new("en-SD", "English (Sudan)"),
        new("en-SE", "English (Sweden)"),
        new("en-SG", "English (Singapore)"),
        new("en-SH", "English (St. Helena)"),
        new("en-SI", "English (Slovenia)"),
        new("en-SL", "English (Sierra Leone)"),
        new("en-SS", "English (South Sudan)"),
        new("en-SX", "English (Sint Maarten)"),
        new("en-SZ", "English (Eswatini)"),
        new("en-TC", "English (Turks & Caicos Islands)"),
        new("en-TK", "English (Tokelau)"),
        new("en-TO", "English (Tonga)"),
        new("en-TT", "English (Trinidad & Tobago)"),
        new("en-TV", "English (Tuvalu)"),
        new("en-TZ", "English (Tanzania)"),
        new("en-UG", "English (Uganda)"),
        new("en-UM", "English (U.S. Outlying Islands)"),
        new("en-US", "English (US)"),
        new("en-VC", "English (St. Vincent & Grenadines)"),
        new("en-VG", "English (British Virgin Islands)"),
        new("en-VI", "English (U.S. Virgin Islands)"),
        new("en-VU", "English (Vanuatu)"),
        new("en-WS", "English (Samoa)"),
        new("en-ZA", "English (South Africa)"),
        new("en-ZM", "English (Zambia)"),
        new("en-ZW", "English (Zimbabwe)"),
        new("es", "Español (España)"),
        new("es-419", "Español (Latinoamérica)"),
        new("es-AR", "Español (Argentina)"),
        new("es-BO", "Español (Bolivia)"),
        new("es-BR", "Español (Brasil)"),
        new("es-BZ", "Español (Belice)"),
        new("es-CL", "Español (Chile)"),
        new("es-CO", "Español (Colombia)"),
        new("es-CR", "Español (Costa Rica)"),
        new("es-CU", "Español (Cuba)"),
        new("es-DO", "Español (República Dominicana)"),
        new("es-EA", "Español (Ceuta y Melilla)"),
        new("es-EC", "Español (Ecuador)"),
        new("es-ES", "Español (España)"),
        new("es-GQ", "Español (Guinea Ecuatorial)"),
        new("es-GT", "Español (Guatemala)"),
        new("es-HN", "Español (Honduras)"),
        new("es-IC", "Español (Canarias)"),
        new("es-MX", "Español (México)"),
        new("es-NI", "Español (Nicaragua)"),
        new("es-PA", "Español (Panamá)"),
        new("es-PE", "Español (Perú)"),
        new("es-PH", "Español (Filipinas)"),
        new("es-PR", "Español (Puerto Rico)"),
        new("es-PY", "Español (Paraguay)"),
        new("es-SV", "Español (El Salvador)"),
        new("es-US", "Español (Estados Unidos)"),
        new("es-UY", "Español (Uruguay)"),
        new("es-VE", "Español (Venezuela)"),
        new("et-EE", "Eesti (Eesti)"),
        new("eu-ES", "Euskara (Espainia)"),
        new("ewo-CM", "Ewondo (Cameroon)"),
        new("fa-AF", "دری (افغانستان)"),
        new("fa-IR", "فارسی (ایران)"),
        new("ff-Adlm-BF", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Burkina Faso)"),
        new("ff-Adlm-CM", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Cameroon)"),
        new("ff-Adlm-GH", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Ghana)"),
        new("ff-Adlm-GM", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Gambia)"),
        new("ff-Adlm-GN", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Guinea)"),
        new("ff-Adlm-GW", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Guinea-Bissau)"),
        new("ff-Adlm-LR", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Liberia)"),
        new("ff-Adlm-MR", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Mauritania)"),
        new("ff-Adlm-NE", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Niger)"),
        new("ff-Adlm-NG", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Nigeria)"),
        new("ff-Adlm-SL", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Sierra Leone)"),
        new("ff-Adlm-SN", "𞤊𞤵𞤤𞤢𞤪 (Adlam, Senegal)"),
        new("fi-FI", "Suomi (Suomi)"),
        new("fil-PH", "Filipino (Pilipinas)"),
        new("fo-DK", "Føroyskt (Danmark)"),
        new("fo-FO", "Føroyskt (Føroyar)"),
        new("fr", "Français (France)"),
        new("fr-BE", "Français (Belgique)"),
        new("fr-BF", "Français (Burkina Faso)"),
        new("fr-BI", "Français (Burundi)"),
        new("fr-BJ", "Français (Bénin)"),
        new("fr-BL", "Français (Saint-Barthélemy)"),
        new("fr-CA", "Français (Canada)"),
        new("fr-CD", "Français (Congo-Kinshasa)"),
        new("fr-CF", "Français (République centrafricaine)"),
        new("fr-CG", "Français (Congo-Brazzaville)"),
        new("fr-CH", "Français (Suisse)"),
        new("fr-CI", "Français (Côte d’Ivoire)"),
        new("fr-CM", "Français (Cameroun)"),
        new("fr-DJ", "Français (Djibouti)"),
        new("fr-DZ", "Français (Algérie)"),
        new("fr-FR", "Français (France)"),
        new("fr-GA", "Français (Gabon)"),
        new("fr-GF", "Français (Guyane française)"),
        new("fr-GN", "Français (Guinée)"),
        new("fr-GP", "Français (Guadeloupe)"),
        new("fr-GQ", "Français (Guinée équatoriale)"),
        new("fr-HT", "Français (Haïti)"),
        new("fr-KM", "Français (Comores)"),
        new("fr-LU", "Français (Luxembourg)"),
        new("fr-MA", "Français (Maroc)"),
        new("fr-MC", "Français (Monaco)"),
        new("fr-MF", "Français (Saint-Martin)"),
        new("fr-MG", "Français (Madagascar)"),
        new("fr-ML", "Français (Mali)"),
        new("fr-MQ", "Français (Martinique)"),
        new("fr-MR", "Français (Mauritanie)"),
        new("fr-MU", "Français (Maurice)"),
        new("fr-NC", "Français (Nouvelle-Calédonie)"),
        new("fr-NE", "Français (Niger)"),
        new("fr-PF", "Français (Polynésie française)"),
        new("fr-PM", "Français (Saint-Pierre-et-Miquelon)"),
        new("fr-RE", "Français (La Réunion)"),
        new("fr-RW", "Français (Rwanda)"),
        new("fr-SC", "Français (Seychelles)"),
        new("fr-SN", "Français (Sénégal)"),
        new("fr-SY", "Français (Syrie)"),
        new("fr-TD", "Français (Tchad)"),
        new("fr-TG", "Français (Togo)"),
        new("fr-TN", "Français (Tunisie)"),
        new("fr-VU", "Français (Vanuatu)"),
        new("fr-WF", "Français (Wallis-et-Futuna)"),
        new("fr-YT", "Français (Mayotte)"),
        new("fur-IT", "Furlan (Italia)"),
        new("fy-NL", "Frysk (Nederlân)"),
        new("ga-GB", "Gaeilge (An Ríocht Aontaithe)"),
        new("ga-IE", "Gaeilge (Éire)"),
        new("gd-GB", "Gàidhlig (An Rìoghachd Aonaichte)"),
        new("gl-ES", "Galego (España)"),
        new("gsw-CH", "Schwiizertüütsch (Schwiiz)"),
        new("gsw-FR", "Alsacien (France)"),
        new("gsw-LI", "Schwiizertüütsch (Liechtenstein)"),
        new("gu-IN", "ગુજરાતી (ભારત)"),
        new("guz-KE", "Gusii (Kenya)"),
        new("gv-IM", "Gaelg (Mannin)"),
        new("ha-GH", "Hausa (Ghana)"),
        new("ha-NE", "Hausa (Nijar)"),
        new("ha-NG", "Hausa (Najeriya)"),
        new("haw-US", "ʻŌlelo Hawaiʻi (US)"),
        new("he-IL", "עברית (ישראל)"),
        new("hi-IN", "हिन्दी (भारत)"),
        new("hi-Latn-IN", "Hindi Latin (India)"),
        new("hr-BA", "Hrvatski (Bosna i Hercegovina)"),
        new("hr-HR", "Hrvatski (Hrvatska)"),
        new("hsb-DE", "Hornjoserbšćina (Němska)"),
        new("hu-HU", "Magyar (Magyarország)"),
        new("hy-AM", "Հայերեն (Հայաստան)"),
        new("ia-001", "Interlingua (World)"),
        new("id-ID", "Bahasa Indonesia (Indonesia)"),
        new("ig-NG", "Igbo (Nigeria)"),
        new("ii-CN", "ꆈꌠꉙ (ꍏꇩ)"),
        new("is-IS", "Íslenska (Ísland)"),
        new("it", "Italiano"),
        new("it-CH", "Italiano (Svizzera)"),
        new("it-IT", "Italiano (Italia)"),
        new("it-SM", "Italiano (San Marino)"),
        new("it-VA", "Italiano (Città del Vaticano)"),
        new("ja", "日本語"),
        new("ja-JP", "日本語 (日本)"),
        new("jgo-CM", "Ndaꞌa (Cameroon)"),
        new("jmc-TZ", "Machame (Tanzania)"),
        new("jv-ID", "Jawa (Indonesia)"),
        new("ka-GE", "ქართული (საქართველო)"),
        new("kab-DZ", "Taqbaylit (Lezzayer)"),
        new("kam-KE", "Kamba (Kenya)"),
        new("kde-TZ", "Makonde (Tanzania)"),
        new("kea-CV", "Kabuverdianu (Kabu Verdi)"),
        new("khq-ML", "Koyra Chiini (Mali)"),
        new("ki-KE", "Gikuyu (Kenya)"),
        new("kk-KZ", "Қазақ тілі (Қазақстан)"),
        new("kkj-CM", "Kako (Cameroon)"),
        new("kl-GL", "Kalaallisut (Kalaallit Nunaat)"),
        new("kln-KE", "Kalenjin (Kenya)"),
        new("km-KH", "ខ្មែរ (កម្ពុជា)"),
        new("kn-IN", "ಕನ್ನಡ (ಭಾರತ)"),
        new("ko", "한국어"),
        new("ko-KP", "한국어 (조선민주주의인민공화국)"),
        new("ko-KR", "한국어 (대한민국)"),
        new("kok-IN", "कोंकणी (भारत)"),
        new("ks-Arab-IN", "کٲشُر (عربی, ہِندوستان)"),
        new("ks-Deva-IN", "कॉशुर (देवनागरी, भारत)"),
        new("ksb-TZ", "Shambala (Tanzania)"),
        new("ksf-CM", "Bafia (Cameroon)"),
        new("ksh-DE", "Kölsch (Deutschland)"),
        new("kw-GB", "Kernewek (Rywvaneth Unys)"),
        new("ky-KG", "Кыргызча (Кыргызстан)"),
        new("lag-TZ", "Langi (Tanzania)"),
        new("lb-LU", "Lëtzebuergesch (Lëtzebuerg)"),
        new("lg-UG", "Luganda (Uganda)"),
        new("lkt-US", "Lakȟólʼiyapi (US)"),
        new("ln-AO", "Lingála (Angóla)"),
        new("ln-CD", "Lingála (Congo-Kinshasa)"),
        new("ln-CF", "Lingála (Ködörösêse tî Bêafrîka)"),
        new("ln-CG", "Lingála (Congo-Brazzaville)"),
        new("lo-LA", "ລາວ (ລາວ)"),
        new("lrc-IQ", "لۊری شومالی (عێراق)"),
        new("lrc-IR", "لۊری شومالی (ئیران)"),
        new("lt-LT", "Lietuvių (Lietuva)"),
        new("lu-CD", "Tshiluba (Congo-Kinshasa)"),
        new("luo-KE", "Dholuo (Kenya)"),
        new("luy-KE", "Luluhia (Kenya)"),
        new("lv-LV", "Latviešu (Latvija)"),
        new("mai-IN", "मैथिली (भारत)"),
        new("mas-KE", "Maa (Kenya)"),
        new("mas-TZ", "Maa (Tanzania)"),
        new("mer-KE", "Kĩmĩrũ (Kenya)"),
        new("mfe-MU", "Kreol Morisien (Moris)"),
        new("mg-MG", "Malagasy (Madagasikara)"),
        new("mgh-MZ", "Makhuwa-Meetto (Moçambique)"),
        new("mgo-CM", "Metaʼ (Cameroon)"),
        new("mi-NZ", "Māori (Aotearoa)"),
        new("mk-MK", "Македонски (Северна Македонија)"),
        new("ml-IN", "മലയാളം (ഇന്ത്യ)"),
        new("mn-MN", "Монгол (Монгол)"),
        new("mni-Beng-IN", "মৈতৈলোন্ (বাংলা, ভারত)"),
        new("mr-IN", "मराठी (भारत)"),
        new("ms-BN", "Bahasa Melayu (Brunei)"),
        new("ms-ID", "Bahasa Melayu (Indonesia)"),
        new("ms-MY", "Bahasa Melayu (Malaysia)"),
        new("ms-SG", "Bahasa Melayu (Singapura)"),
        new("mt-MT", "Malti (Malta)"),
        new("mua-CM", "Mundang (Cameroon)"),
        new("my-MM", "မြန်မာ (မြန်မာ)"),
        new("mzn-IR", "مازِرونی (ایران)"),
        new("naq-NA", "Khoekhoegowab (Namibia)"),
        new("nb-NO", "Norsk bokmål (Norge)"),
        new("nb-SJ", "Norsk bokmål (Svalbard og Jan Mayen)"),
        new("nd-ZW", "isiNdebele (Zimbabwe)"),
        new("nds-DE", "Neddersass’sch (Düütschland)"),
        new("nds-NL", "Nedersaksies (Nederlaand)"),
        new("ne-IN", "नेपाली (भारत)"),
        new("ne-NP", "नेपाली (नेपाल)"),
        new("nl-AW", "Nederlands (Aruba)"),
        new("nl-BE", "Nederlands (België)"),
        new("nl-BQ", "Nederlands (Caribisch Nederland)"),
        new("nl-CW", "Nederlands (Curaçao)"),
        new("nl-NL", "Nederlands (Nederland)"),
        new("nl-SR", "Nederlands (Suriname)"),
        new("nl-SX", "Nederlands (Sint Maarten)"),
        new("nmg-CM", "Kwasio (Cameroon)"),
        new("nn-NO", "Norsk nynorsk (Noreg)"),
        new("nnh-CM", "Ngiemboon (Cameroon)"),
        new("no-NO", "Norsk (Norge)"),
        new("nus-SS", "Thok Nath (South Sudan)"),
        new("nyn-UG", "Runyankore (Uganda)"),
        new("om-ET", "Oromoo (Itoophiyaa)"),
        new("om-KE", "Oromoo (Keeniyaa)"),
        new("or-IN", "ଓଡ଼ିଆ (ଭାରତ)"),
        new("os-GE", "Ирон (Гуырдзыстон)"),
        new("os-RU", "Ирон (Уӕрӕсе)"),
        new("pa-Arab-PK", "پنجابی (پاکستان)"),
        new("pa-Guru-IN", "ਪੰਜਾਬੀ (ਭਾਰਤ)"),
        new("pcm-NG", "Nigerian Pidgin (Nigeria)"),
        new("pl-PL", "Polski (Polska)"),
        new("ps-AF", "پښتو (افغانستان)"),
        new("ps-PK", "پښتو (پاکستان)"),
        new("pt-AO", "Português (Angola)"),
        new("pt-BR", "Português (Brasil)"),
        new("pt-CH", "Português (Suíça)"),
        new("pt-CV", "Português (Cabo Verde)"),
        new("pt-GQ", "Português (Guiné Equatorial)"),
        new("pt-GW", "Português (Guiné-Bissau)"),
        new("pt-LU", "Português (Luxemburgo)"),
        new("pt-MO", "Português (Macau)"),
        new("pt-MZ", "Português (Moçambique)"),
        new("pt-PT", "Português (Portugal)"),
        new("pt-ST", "Português (São Tomé e Príncipe)"),
        new("pt-TL", "Português (Timor-Leste)"),
        new("qu-BO", "Runasimi (Bolivia)"),
        new("qu-EC", "Runasimi (Ecuador)"),
        new("qu-PE", "Runasimi (Perú)"),
        new("raj-IN", "राजस्थानी (भारत)"),
        new("rm-CH", "Rumantsch (Svizra)"),
        new("rn-BI", "Ikirundi (Uburundi)"),
        new("ro-MD", "Română (Republica Moldova)"),
        new("ro-RO", "Română (România)"),
        new("rof-TZ", "Kihorombo (Tanzania)"),
        new("ru", "Русский"),
        new("ru-BY", "Русский (Беларусь)"),
        new("ru-KG", "Русский (Киргизия)"),
        new("ru-KZ", "Русский (Казахстан)"),
        new("ru-MD", "Русский (Молдова)"),
        new("ru-RU", "Русский (Россия)"),
        new("ru-UA", "Русский (Украина)"),
        new("rw-RW", "Kinyarwanda (Rwanda)"),
        new("rwk-TZ", "Kiruwa (Tanzania)"),
        new("sa-IN", "संस्कृतम् (भारत)"),
        new("sah-RU", "Саха тыла (Россия)"),
        new("saq-KE", "Samburu (Kenya)"),
        new("sat-Olck-IN", "ᱥᱟᱱᱛᱟᱲᱤ (ᱚᱞ ᱪᱤᱠᱤ, ᱥᱤᱧᱚᱛ)"),
        new("sbp-TZ", "Ishisangu (Tanzania)"),
        new("sd-Arab-PK", "سنڌي (پاکستان)"),
        new("sd-Deva-IN", "सिन्धी (भारत)"),
        new("se-FI", "Davvisámegiella (Suopma)"),
        new("se-NO", "Davvisámegiella (Norga)"),
        new("se-SE", "Davvisámegiella (Ruoŧŧa)"),
        new("seh-MZ", "Sena (Moçambique)"),
        new("ses-ML", "Koyraboro Senni (Mali)"),
        new("sg-CF", "Sängö (Ködörösêse tî Bêafrîka)"),
        new("shi-Latn-MA", "Tachelhit (Latin, Morocco)"),
        new("shi-Tfng-MA", "ⵜⴰⵛⵍⵃⵉⵜ (ⵜⴼⵉⵏⴰⵖ, Morocco)"),
        new("si-LK", "සිංහල (ශ්‍රී ලංකාව)"),
        new("sk-SK", "Slovenčina (Slovensko)"),
        new("sl-SI", "Slovenščina (Slovenija)"),
        new("smn-FI", "Anarâškielâ (Suomâ)"),
        new("sn-ZW", "chiShona (Zimbabwe)"),
        new("so-DJ", "Soomaali (Jabuuti)"),
        new("so-ET", "Soomaali (Itoobiya)"),
        new("so-KE", "Soomaali (Kenya)"),
        new("so-SO", "Soomaali (Soomaaliya)"),
        new("sq-AL", "Shqip (Shqipëri)"),
        new("sq-MK", "Shqip (Maqedonia e Veriut)"),
        new("sq-XK", "Shqip (Kosovë)"),
        new("sr-Cyrl-BA", "Српски (ћирилица, БиХ)"),
        new("sr-Cyrl-ME", "Српски (ћирилица, Црна Гора)"),
        new("sr-Cyrl-RS", "Српски (ћирилица, Србија)"),
        new("sr-Cyrl-XK", "Српски (ћирилица, Косово)"),
        new("sr-Latn-BA", "Srpski (latinica, BiH)"),
        new("sr-Latn-ME", "Srpski (latinica, Crna Gora)"),
        new("sr-Latn-RS", "Srpski (latinica, Srbija)"),
        new("sr-Latn-XK", "Srpski (latinica, Kosovo)"),
        new("su-Latn-ID", "Basa Sunda (Latin, Indonesia)"),
        new("sv-AX", "Svenska (Åland)"),
        new("sv-FI", "Svenska (Finland)"),
        new("sv-SE", "Svenska (Sverige)"),
        new("sw-CD", "Kiswahili (Congo-Kinshasa)"),
        new("sw-KE", "Kiswahili (Kenya)"),
        new("sw-TZ", "Kiswahili (Tanzania)"),
        new("sw-UG", "Kiswahili (Uganda)"),
        new("ta-IN", "தமிழ் (இந்தியா)"),
        new("ta-LK", "தமிழ் (இலங்கை)"),
        new("ta-MY", "தமிழ் (மலேசியா)"),
        new("ta-SG", "தமிழ் (சிங்கப்பூர்)"),
        new("te-IN", "తెలుగు (భారతదేశం)"),
        new("teo-KE", "Kiteso (Kenya)"),
        new("teo-UG", "Kiteso (Uganda)"),
        new("tg-TJ", "Тоҷикӣ (Тоҷикистон)"),
        new("th-TH", "ไทย (ไทย)"),
        new("ti-ER", "ትግርኛ (ኤርትራ)"),
        new("ti-ET", "ትግርኛ (ኢትዮጵያ)"),
        new("tk-TM", "Türkmençe (Türkmenistan)"),
        new("to-TO", "Lea fakatonga (Tonga)"),
        new("tr-CY", "Türkçe (Kıbrıs)"),
        new("tr-TR", "Türkçe (Türkiye)"),
        new("tt-RU", "Татар (Россия)"),
        new("twq-NE", "Tasawaq (Niger)"),
        new("tzm-MA", "Tamaziɣt (Maroc)"),
        new("ug-CN", "ئۇيغۇرچە (جۇڭگو)"),
        new("uk-UA", "Українська (Україна)"),
        new("ur-IN", "اردو (بھارت)"),
        new("ur-PK", "اردو (پاکستان)"),
        new("uz-Arab-AF", "اوزبیک (افغانستان)"),
        new("uz-Cyrl-UZ", "Ўзбекча (Кирилл, Ўзбекистон)"),
        new("uz-Latn-UZ", "Oʻzbek (lotin, Oʻzbekiston)"),
        new("vai-Latn-LR", "Vai (Latin, Liberia)"),
        new("vai-Vaii-LR", "ꕙꔤ (Vai, Liberia)"),
        new("vi-VN", "Tiếng Việt (Việt Nam)"),
        new("vo-001", "Volapük (World)"),
        new("vun-TZ", "Kivunjo (Tanzania)"),
        new("wae-CH", "Walser (Schweiz)"),
        new("wo-SN", "Wolof (Sénégal)"),
        new("xh-ZA", "isiXhosa (South Africa)"),
        new("xog-UG", "Soga (Uganda)"),
        new("yav-CM", "Yangben (Cameroon)"),
        new("yi-001", "ייִדיש (וועלט)"),
        new("yo-BJ", "Èdè Yorùbá (Bẹ̀nẹ̀)"),
        new("yo-NG", "Èdè Yorùbá (Nàìjíríà)"),
        new("yue-Hans-CN", "粤语 (简体，中国)"),
        new("yue-Hant-HK", "粵語 (繁體，香港)"),
        new("zgh-MA", "ⵜⴰⵎⴰⵣⵉⵖⵜ (ⵍⵎⵖⵔⵉⴱ)"),
        new("zh-CN", "简体中文"),
        new("zh-Hans-CN", "简体中文（中国）"),
        new("zh-Hans-HK", "简体中文（香港）"),
        new("zh-Hans-MO", "简体中文（澳门）"),
        new("zh-Hans-SG", "简体中文（新加坡）"),
        new("zh-Hant-HK", "繁體中文（香港）"),
        new("zh-Hant-MO", "繁體中文（澳門）"),
        new("zh-Hant-TW", "繁體中文（台灣）"),
        new("zh-HK", "繁體中文（香港）"),
        new("zh-TW", "繁體中文（台灣）"),
        new("zu-ZA", "isiZulu (South Africa)"),
    ];
}
